#ifndef PARTITIONSGENERATION_INTEGERPARTITIONSGENERATOR_H
#define PARTITIONSGENERATION_INTEGERPARTITIONSGENERATOR_H
#include "PartitionsGenerator.h"

class IntegerPartitionsGenerator : public PartitionsGenerator
{
};

#endif //PARTITIONSGENERATION_INTEGERPARTITIONSGENERATOR_H
